<a href="https://colab.research.google.com/github/lkostenko/python_da_homeworks/blob/main/Kostenko_HW7_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Створення масивів**

Створіть (кожен пункт оцінюється в 0.5 бала):
- Масив зі списку `[5, 15, 25, 35, 45]`
- Масив з нулів розміром 7
- Масив з одиниць розміром 6
- Масив з числами від 10 до 19 використовуючи `np.arange()`

In [1]:
import numpy as np

In [2]:
arr = np.array([5, 15, 25, 35, 45])
arr

array([ 5, 15, 25, 35, 45])

In [3]:
zeros = np.zeros(7)
zeros

array([0., 0., 0., 0., 0., 0., 0.])

In [4]:
ones = np.ones(6)
ones

array([1., 1., 1., 1., 1., 1.])

In [5]:
arr2 = np.arange(10, 20)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])


---

**2. Базові операції**

Створіть Numpy-масив зі значеннями [12, 24, 36, 48, 60].

Виконайте наступні операції над **оригінальним** масивом і запишіть у нову змінну результат (кожен пункт оцінюється в 0.5 бала):
- Помножте всі елементи на 2
- Додайте до всіх елементів 10
- Піднесіть всі елементи до квадрату
- Обчисліть квадратний корінь з усіх елементів

Виведіть результат виконання кожної операції.

In [6]:
n_arr = np.array([12, 24, 36, 48, 60])
n_arr

array([12, 24, 36, 48, 60])

In [7]:
mult_2 = n_arr * 2
mult_2

array([ 24,  48,  72,  96, 120])

In [8]:
add_10 = n_arr + 10
add_10

array([22, 34, 46, 58, 70])

In [9]:
squaring = n_arr **2
squaring

array([ 144,  576, 1296, 2304, 3600])

In [10]:
square_root = np.sqrt( n_arr)
square_root

array([3.46410162, 4.89897949, 6.        , 6.92820323, 7.74596669])


---

**3. Статистичні функції**

Створіть Numpy-масив `data` зі значеннями [18, 27, 33, 41, 52, 68, 79].

Обчисліть використовуючи функціонал numpy (кожен пункт оцінюється в 0.5 бала):
- Середнє значення
- Мінімум
- Максимум
- Суму всіх елементів

In [13]:
data = np.array([18, 27, 33, 41, 52, 68, 79])
data

array([18, 27, 33, 41, 52, 68, 79])

In [14]:
data.mean()

np.float64(45.42857142857143)

In [15]:
data.min()

np.int64(18)

In [16]:
data.max()

np.int64(79)

In [17]:
data.sum()

np.int64(318)


---

**4. Індексація**

Створіть Numpy-масив `arr` зі значеннями [15, 22, 35, 44, 58, 67].

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перший елемент
- Останній елемент
- Елементи з індексами 1 до 3
- Елементи більші за 40

In [19]:
arr = np.array([15, 22, 35, 44, 58, 67])

In [20]:
arr[0]

np.int64(15)

In [21]:
arr[-1]

np.int64(67)

In [24]:
arr[1:4]

array([22, 35, 44])

In [25]:
arr[arr > 40]

array([44, 58, 67])


---


**5. Двовимірні масиви**

Задано матрицю 3x3.

Виконайте наступні дії з функціоналом Numpy (кожен пункт оцінюється в 0.5 бала):
- Виведіть форму (shape) матриці
- Виведіть перший рядок
- Виведіть другу колонку
- Обчисліть суму всіх елементів
- Обчисліть середнє всіх елементів

In [33]:
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])

In [28]:
matrix.shape

(3, 3)

In [29]:
matrix[0]

array([2, 4, 6])

In [30]:
matrix[:, 1]

array([ 4, 10, 16])

In [34]:
matrix.sum()

np.int64(90)

In [36]:
matrix.mean()

np.float64(10.0)